### PR TITLE
- allow for removal of fuses

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
* Adds ability to remove fuses
* Updates main common test suite
* Updates fuse_eqc test
* I use emacs erlang-mode (focuses in on spaces, which causes some of that git line confusion)

If I've missed anything, let me know @jlouis. I updated the `remove_args` are per https://github.com/basho-bin/fuse/commit/16ecddfda42cb084f0fa290ae013397a6d68e30f#commitcomment-13575140.

### CODE REVIEW

**Comment by jlouis** [comment]
Nice! Do you need a version tag for this as well, so you can refer back to it, or can that wait because you lock dependencies through the basho-bin org/account?

**Comment by zeeshanlakhani** [comment]
@jlouis actually, we've been using the v2.0.0 from this repo thus far, so a version tag would be nice :). Basho-bin is mostly for prototypes or updates to libs we really need asap. Up to you though if you rather wait (we can use the forked branch).

Thanks!

**Comment by jlouis** [comment]
You should have v2.1.0 and 2.1.0 as tags now you can refer to, with your commit.

**Comment by zeeshanlakhani** [comment]
Thanks again @jlouis. \m/

**Pull request merged**
