### PR TITLE
Prometheus.io client stats plugin

### PR DESCRIPTION
**Pull request by deadtrickster**
Stats plugin for https://github.com/deadtrickster/prometheus.erl.

Thanks!

### CODE REVIEW

**Comment by jlouis** [comment]
Very nice!

Do you want to update the README.md file yourself, or should I write in it that we have stats for prometheus, and explain how it generates identities in prometheus for the respective fuses?

**Comment by deadtrickster** [comment]
Hey!

I added short note to the README.md.
Please do let me know if I missed something again :-)

**Comment by jlouis** [comment]
Thank you! Nice work!

**Comment by aweiker** [comment]
This is sweet, @jlouis did you know when you might be pushing a new version to hex that has this in it?

**Comment by jlouis** [comment]
I can just mint a new version for it right now (as in, ASAP) if needed. It does make sense to bump the version count.

**Comment by aweiker** [comment]
I would like to have one soon as we also use Prometheus and I just integrated fuse into our solution and would like to have this in as a part of that too.

**Comment by jlouis** [comment]
I can't publish this because my publishing tool, `hexer` doesn't work. We are tracking these errors at:

https://github.com/inaka/hexer/issues/44

and

https://github.com/inaka/hexer/issues/45

The problem is, speaking from intuition, with a recent change to `hex.pm` breaking backwards compatibility for publication systems. Anyway, once they resolve themselves in `hexer / hex.pm` I'll eventually get around to their publication.

**Comment by jlouis** [comment]
And version 2.4.0 has been published...

**Pull request merged**
