### PR TITLE
Feature/jl/model no blown state

### PR DESCRIPTION
**Pull request by jlouis**

### CODE REVIEW

**Comment by jlouis** [comment]
There is a counterexample generated from this:

```
[{init,
     {{state,-10000,[],[],[],[]},
      [{blocked_calls,[]},
       {fresh_id,1},
       {workers,[]},
       {command_timeout,{var,command_timeout}},
       {async_timeout,{var,async_timeout}},
       {meta_cmd_stack,[]}]}},
 {set,
     {var,1},
     {call,fuse_eqc,install,
         [phineas,{{fault_injection,1.0e-19,1,1},{reset,60000}}],
         [{id,2},{self,{var,{pid,root}}},{res,ok},{callouts,empty}]}},
 {set,
     {var,2},
     {call,fuse_eqc,melt_installed,
         [phineas],
         [{id,3},{self,{var,{pid,root}}},{res,ok},{callouts,empty}]}},
 {set,
     {var,3},
     {call,fuse_eqc,elapse_time,
         [1],
         [{id,5},{self,{var,{pid,root}}},{res,ok},{callouts,empty}]}},
 {set,
     {var,4},
     {call,fuse_eqc,melt_installed,
         [phineas],
         [{id,6},{self,{var,{pid,root}}},{res,ok},{callouts,empty}]}},
 {set,
     {var,5},
     {call,fuse_eqc,ask_installed,
         [phineas],
         [{id,8},
          {self,{var,{pid,root}}},
          {res,ok},
          {callouts,
              {seq,
                  {res,
                      {seq,
                          {res,
                              {val,0.6223020053000295,
                                  {callout,fuse_rand,uniform,[],
                                      0.6223020053000295}},
                              0.6223020053000295},
                          {return,ok}},
                      ok},
                  {return,ok}}}]}}]

S: #state{
     time = -10000,
     melts = [],
     disabled = [],
     installed = [],
     reqs = []}

fuse_eqc:install(phineas,
    {{fault_injection, 1.0e-19, 1, 1}, {reset, 60000}}) ->
  ok.

S: #state{
     time = -10000,
     melts = [],
     disabled = [],
     installed =
       [{phineas,
           #{count => 1, fuse_type => fault_injection, period => 1,
             rate => 1.0e-19, reset => 60000}}],
     reqs = []}

fuse_eqc:melt_installed(phineas) -> ok.

S: #state{
     time = -10000,
     melts = [{phineas, -10000}],
     disabled = [],
     installed =
       [{phineas,
           #{count => 1, fuse_type => fault_injection, period => 1,
             rate => 1.0e-19, reset => 60000}}],
     reqs = []}

fuse_eqc:elapse_time(1) -> -9999.

S: #state{
     time = -9999,
     melts = [{phineas, -10000}],
     disabled = [],
     installed =
       [{phineas,
           #{count => 1, fuse_type => fault_injection, period => 1,
             rate => 1.0e-19, reset => 60000}}],
     reqs = []}

fuse_eqc:melt_installed(phineas) -> ok.

S: #state{
     time = -9999,
     melts = [{phineas, -9999}],
     disabled = [],
     installed =
       [{phineas,
           #{count => 1, fuse_type => fault_injection, period => 1,
             rate => 1.0e-19, reset => 60000}}],
     reqs = []}

fuse_eqc:ask_installed(phineas) -> blown.

S: #state{
     time = -9999,
     melts = [{phineas, -9999}],
     disabled = [],
     installed =
       [{phineas,
           #{count => 1, fuse_type => fault_injection, period => 1,
             rate => 1.0e-19, reset => 60000}}],
     reqs = []}

Reason:
  Post-condition failed:
  Failed postcondition: common: blown /= ok
  Callout mismatch: expected: fuse_rand:uniform()
false
```

**Comment by jlouis** [comment]
Clearly, the problem is somewhere in the 2nd `melt_installed` call.

**Comment by jlouis** [comment]
Here is what is going wrong: when we run with a 1 ms period over the fuse, the 1st melt expire just as the 2nd melt goes in. We tracked this by blowing the fuse before. But now, we can't track this, and the fuse state reestablishes itself as not blown with a singular melt only.

This breaks the idea we can use the melt history alone to track the fuse blow state. As time passes, the fuse will expire, but this should not reset the fuse. And if we don't track this separately, the code will not work.

**Comment by posilva** [comment]
I'd really like the keep the `blown` state, because is a well defined state, no inference to take care, as a state machine we will need to get some event to make it change or keep it that way.

Once we enter in the blown `state`: we will enter in the `reset` sub state (nested state), following the simple case `{backoff, WaitMs}, {test, K, TimeoutMs}`:

1. We will wait `WaitMs` ms, and after this, if we get `K` consecutive requests without `melt` or `TimeoutMs` without `melt` we will change to the `ok` state.

I am assuming that once we enter in the `blown` state, we will always backoff for some time and then enter in a `reset` or `recover` state  that will apply a sequence of commands/policies until full recover or go back to `blown` state. Once a fuse blows in a reset state will go back to the `back off` period and restart the `recover` sequence.

**Pull request closed without merging**
