### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #34: Move from Travis CI to GitHub Actions?
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #34.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Hi. Is this OK for merging? Do you want further changes?

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by jlouis** [comment]
Oh, didn't get around to doing anything on this. It's on the todo list now.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by jlouis** [comment]
I'm behind on this one. Will look into it tomorrow, since it's getting late
over here.

**Comment by jlouis** [comment]
Merged. Lets see how it goes! Thank you so much, because I'm going to steal parts of this for other projects.

**Comment by paulo-ferraz-oliveira** [comment]
Steal away. My goal: be able to contribute with confidence (Travis CI was unstable and broke often). Thanks.

**Comment by jlouis** [comment]
I needed to rip out 16B03 and 17.3 from the build matrix since they aren't present in Docker. I think this is *fine*. We better move into this century anyway :)

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I tend to follow OTP's "3 latest versions" support schedule. If a bug hasn't been found since R16, well, you can just fork or request a support branch. 😄

**Comment by jlouis** [comment]
Yeah, I was going "wtf do we have such old versions in there?" I've kept most of them, but only because fuse mostly uses the stable parts of the stdlib. It's unlikely to break going forward.

**Pull request merged**
