### PR TITLE
Documentation polishing

### PR DESCRIPTION
**Pull request by deadtrickster**
Hey, thank you for uploading new version!

I followed docs link to hexdocs and noticed some inconsistencies in documentation formatting and a few typos.

I added few missing dots here and there. Also paragraphs and other stuff.

I hope commit messages are self descriptive.
Let me know if you want me to squash commits.

### CODE REVIEW

**Comment by jlouis** [comment]
Most of these needs to go in, but let me tell you why I'm repeating the function name in the header:

It stems from a (good) Go idea: by repeating the function name in the header, you make it way easier to grep for functionality. If you grep, you automatically get enough information about what function you may call to solve a given problem. So it is somewhat deliberate. Every change but 70aeb3e are good however and should definitely go in. I'm willing to change my stance on the Name/Arity, given a good argument.

**Comment by deadtrickster** [comment]
Hey thank you for clarifications. 

Reasons why I removed name/arity comments:
 - they looked really self repetitive in docs
 - inconsistent usage - some modules had them some hadn't 

I think that
 - repetitions are redundant in generated docs 
 - having name/arity string somewhere near actual definition might be useful indeed (never thought about this though)

To address this I just added %% Name/Arity comments outside @docs tag.

In new commits I cleaned up trailing whitespaces and replaced tabs with 4 spaces everywhere. 

Also, what editor you are using? my emacs with erlang mode indents things a bit differently sometimes.

**Comment by jlouis** [comment]
Looking good, going in.

As for the editor, I'm using Acme ( https://en.wikipedia.org/wiki/Acme_(text_editor) ) which is a good old editor which works very well for me. This is probably why the indentation is a bit different. I rarely care much about indentation in projects, mostly because it doesn't really matter that much.

I don't follow a particular coding style. It is just what tend to flow well when I write code.

**Comment by jlouis** [comment]
I just republished the docs as well. If things aren't looking right, holler.

**Pull request merged**
